package quicklook

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeTemp(t *testing.T, name, body string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

// A preview must be one self-contained file: the sandbox grants no asset
// server, and Quick Look fetches nothing.
func TestRenderIsSelfContained(t *testing.T) {
	path := writeTemp(t, "doc.md", "# Title\n\n```go\nvar x = 1\n```\n\n> [!NOTE]\n> hi\n")
	out := Render(path, false)

	for _, want := range []string{
		"<!DOCTYPE html>", "<title>Title</title>", "<style>", "markdown-alert", "chroma",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("preview missing %q", want)
		}
	}
	for _, forbidden := range []string{
		"<script", "<link", "/doc-asset/", "src=\"http", "@import",
	} {
		if strings.Contains(out, forbidden) {
			t.Errorf("preview is not self-contained, contains %q", forbidden)
		}
	}
}

func TestRenderInlinesLocalImages(t *testing.T) {
	dir := t.TempDir()
	png := []byte("\x89PNG\r\n\x1a\n" + strings.Repeat("x", 32))
	if err := os.WriteFile(filepath.Join(dir, "pixel.png"), png, 0o600); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(dir, "doc.md")
	if err := os.WriteFile(path, []byte("![a pixel](pixel.png)\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	out := Render(path, false)
	if !strings.Contains(out, "data:image/png;base64,") {
		t.Errorf("local image was not inlined: %q", out)
	}
	if strings.Contains(out, "/doc-asset/") {
		t.Error("an asset route survived into the preview")
	}
}

// An image the sandbox will not let us read must not break the document.
func TestRenderSurvivesAnUnreadableImage(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "doc.md")
	if err := os.WriteFile(path, []byte("![missing](nope.png)\n\nAfter.\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	out := Render(path, false)
	if !strings.Contains(out, "After.") {
		t.Errorf("document was truncated by an unreadable image: %q", out)
	}
	if !strings.Contains(out, `alt="missing"`) {
		t.Errorf("alt text was lost: %q", out)
	}
}

func TestRenderOfAMissingFileExplainsItself(t *testing.T) {
	out := Render(filepath.Join(t.TempDir(), "gone.md"), false)
	if !strings.Contains(out, "Cannot preview gone.md") {
		t.Errorf("expected an error page, got %q", out)
	}
	if !strings.Contains(out, "<style>") {
		t.Error("error page is unstyled")
	}
}

func TestRenderHonoursTheDarkTheme(t *testing.T) {
	path := writeTemp(t, "doc.md", "# T\n")
	if !strings.Contains(Render(path, true), `data-theme="dark"`) {
		t.Error("dark preview did not set data-theme")
	}
	if !strings.Contains(Render(path, false), `data-theme="light"`) {
		t.Error("light preview did not set data-theme")
	}
}

// The generated stylesheet must stay in sync with the app's, or a preview and
// the window it precedes will disagree about how a document looks. CI runs
// tools/gen-preview-css and checks for a diff; this catches the simpler case of
// the file having been emptied or hand-edited into uselessness.
func TestStylesheetLooksGenerated(t *testing.T) {
	if !strings.HasPrefix(previewCSS, "/* GENERATED by tools/gen-preview-css") {
		t.Error("styles.css lost its generated-file header — was it hand-edited?")
	}
	for _, want := range []string{"--alert-note", ".chroma", "article table", ".preview-error"} {
		if !strings.Contains(previewCSS, want) {
			t.Errorf("styles.css is missing %q; regenerate with go run ./tools/gen-preview-css", want)
		}
	}
}
