// Command gen-preview-css builds internal/quicklook/styles.css, the stylesheet
// the Quick Look preview inlines into every document it renders.
//
// It is a concatenation of the app's own theme.css and chroma.css plus a short
// preview-only addendum, rather than a hand-written copy, so a preview can
// never drift from the window it is previewing. The app-chrome rules (#toolbar,
// #appearance-menu, the copy button) come along and simply match nothing —
// cheaper and far more reliable than trying to strip them.
//
// Run it after changing either stylesheet; CI checks the result is in sync.
package main

import (
	"fmt"
	"os"
	"strings"
)

const out = "internal/quicklook/styles.css"

// addendum restores what the app gets from its shell but a preview has no room
// for: the article is the whole page here, and errors need somewhere to show.
const addendum = `
/* ---------- Quick Look preview only (tools/gen-preview-css) ---------- */

/* The preview panel is the document: no toolbar to leave room for, and a
   narrower comfortable measure than a resizable window. */
body {
  padding: 18px 22px 28px;
}

article {
  max-width: 68ch;
}

article > :first-child {
  margin-top: 0;
}

.preview-error {
  color: var(--error-fg);
  background: var(--error-bg);
  border: 1px solid var(--error-border);
  border-radius: 8px;
  padding: 10px 14px;
}

/* Quick Look does not run scripts, so math and diagrams stay as source. Mark
   them as such instead of letting them look like broken output. */
article pre.math-display,
article code.language-math,
article code.language-mermaid {
  color: var(--fg-muted);
}
`

func main() {
	var b strings.Builder
	b.WriteString("/* GENERATED by tools/gen-preview-css — do not edit.\n" +
		"   Source: frontend/src/theme.css + frontend/src/chroma.css */\n")
	for _, src := range []string{"frontend/src/theme.css", "frontend/src/chroma.css"} {
		data, err := os.ReadFile(src)
		if err != nil {
			fmt.Fprintln(os.Stderr, "gen-preview-css:", err)
			os.Exit(1)
		}
		b.WriteString("\n/* ===== " + src + " ===== */\n")
		b.Write(data)
	}
	b.WriteString(addendum)
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "gen-preview-css:", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d bytes)\n", out, b.Len())
}
