// Command gen-chroma generates frontend/src/chroma.css: class-based chroma
// highlighting styles — a light theme on bare selectors and a dark theme
// scoped under [data-theme="dark"]. The frontend resolves theme=system to a
// concrete data-theme attribute, so no prefers-color-scheme block is needed.
//
// Run from the repo root:
//
//	go run ./tools/gen-chroma
package main

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"strings"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
)

const outPath = "frontend/src/chroma.css"

func main() {
	formatter := chromahtml.New(chromahtml.WithClasses(true))

	var light, dark bytes.Buffer
	if err := formatter.WriteCSS(&light, styles.Get("github")); err != nil {
		log.Fatalf("write light css: %v", err)
	}
	if err := formatter.WriteCSS(&dark, styles.Get("github-dark")); err != nil {
		log.Fatalf("write dark css: %v", err)
	}

	var out bytes.Buffer
	out.WriteString("/* Generated by `go run ./tools/gen-chroma` — do not edit by hand. */\n")
	out.WriteString("/* Light (chroma style: github) */\n")
	out.Write(light.Bytes())
	out.WriteString("\n/* Dark (chroma style: github-dark), scoped to [data-theme=\"dark\"] */\n")
	out.WriteString(prefixSelectors(dark.String(), `[data-theme="dark"] `))

	if err := os.WriteFile(outPath, out.Bytes(), 0o644); err != nil {
		log.Fatalf("write %s: %v", outPath, err)
	}
	fmt.Printf("wrote %s (%d bytes)\n", outPath, out.Len())
}

// prefixSelectors prepends prefix to every selector in the simple one-rule-
// per-line CSS chroma emits (`/* Name */ .chroma .x { ... }`).
func prefixSelectors(css, prefix string) string {
	var b strings.Builder
	for _, line := range strings.Split(css, "\n") {
		brace := strings.Index(line, "{")
		if brace < 0 {
			b.WriteString(line)
			b.WriteString("\n")
			continue
		}
		head, tail := line[:brace], line[brace:]
		comment := ""
		selectors := head
		if i := strings.LastIndex(head, "*/"); i >= 0 {
			comment = head[:i+2]
			selectors = head[i+2:]
		}
		parts := strings.Split(selectors, ",")
		for j, p := range parts {
			parts[j] = prefix + strings.TrimSpace(p)
		}
		b.WriteString(comment)
		b.WriteString(" ")
		b.WriteString(strings.Join(parts, ", "))
		b.WriteString(" ")
		b.WriteString(tail)
		b.WriteString("\n")
	}
	return b.String()
}
