// Command gen-chroma generates frontend/src/chroma.css: class-based chroma
// highlighting styles for every app theme — a light theme on bare selectors,
// a dark theme scoped under [data-theme="dark"], a warm sepia theme scoped
// under [data-theme="sepia"], and a prefers-color-scheme dark block scoped
// under [data-theme="system"] so a server-inlined system theme paints
// correctly before the frontend resolves it to a concrete theme.
//
// Run from the repo root:
//
//	go run ./tools/gen-chroma
package main

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"strings"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
)

const outPath = "frontend/src/chroma.css"

func styleCSS(styleName string) string {
	formatter := chromahtml.New(chromahtml.WithClasses(true))
	style := styles.Get(styleName)
	if style == nil {
		log.Fatalf("unknown chroma style %q", styleName)
	}
	var buf bytes.Buffer
	if err := formatter.WriteCSS(&buf, style); err != nil {
		log.Fatalf("write css for %s: %v", styleName, err)
	}
	return buf.String()
}

func main() {
	light := styleCSS("github")
	dark := styleCSS("github-dark")
	sepia := styleCSS("solarized-light")

	var out bytes.Buffer
	out.WriteString("/* Generated by `go run ./tools/gen-chroma` — do not edit by hand. */\n")
	out.WriteString("/* Light (chroma style: github) */\n")
	out.WriteString(light)
	out.WriteString("\n/* Dark (chroma style: github-dark), scoped to [data-theme=\"dark\"] */\n")
	out.WriteString(prefixSelectors(dark, `[data-theme="dark"] `))
	out.WriteString("\n/* Sepia (chroma style: solarized-light — warm on #f4ecd8), scoped to [data-theme=\"sepia\"] */\n")
	out.WriteString(prefixSelectors(sepia, `[data-theme="sepia"] `))
	out.WriteString("\n/* System theme before JS resolves it: dark palette under prefers-color-scheme,\n")
	out.WriteString("   scoped to [data-theme=\"system\"] (inlined server-side for first paint). */\n")
	out.WriteString("@media (prefers-color-scheme: dark) {\n")
	out.WriteString(prefixSelectors(dark, `[data-theme="system"] `))
	out.WriteString("}\n")

	if err := os.WriteFile(outPath, out.Bytes(), 0o644); err != nil {
		log.Fatalf("write %s: %v", outPath, err)
	}
	fmt.Printf("wrote %s (%d bytes)\n", outPath, out.Len())
}

// prefixSelectors prepends prefix to every selector in the simple one-rule-
// per-line CSS chroma emits (`/* Name */ .chroma .x { ... }`).
func prefixSelectors(css, prefix string) string {
	var b strings.Builder
	for _, line := range strings.Split(css, "\n") {
		brace := strings.Index(line, "{")
		if brace < 0 {
			b.WriteString(line)
			b.WriteString("\n")
			continue
		}
		head, tail := line[:brace], line[brace:]
		comment := ""
		selectors := head
		if i := strings.LastIndex(head, "*/"); i >= 0 {
			comment = head[:i+2]
			selectors = head[i+2:]
		}
		parts := strings.Split(selectors, ",")
		for j, p := range parts {
			parts[j] = prefix + strings.TrimSpace(p)
		}
		b.WriteString(comment)
		b.WriteString(" ")
		b.WriteString(strings.Join(parts, ", "))
		b.WriteString(" ")
		b.WriteString(tail)
		b.WriteString("\n")
	}
	return b.String()
}
