// Package render implements the markdown rendering pipeline:
// goldmark (GFM) -> chroma (class-based syntax highlighting) -> bluemonday (sanitization).
package render

import (
	"bytes"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/microcosm-cc/bluemonday"
	"github.com/yuin/goldmark"
	highlighting "github.com/yuin/goldmark-highlighting/v2"
	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/parser"
	"github.com/yuin/goldmark/renderer/html"
	"github.com/yuin/goldmark/text"
)

// AssetRoutePrefix is the in-app URL prefix that serves scope-checked local files
// (images referenced by documents). The absolute file path travels in the "p"
// query parameter, URL-encoded.
const AssetRoutePrefix = "/doc-asset/"

// maxHighlightFenceBytes caps syntax highlighting: any single code fence whose
// content is larger than this renders as a plain escaped <pre><code> block
// instead of going through chroma. Chroma tokenization costs seconds per
// megabyte, which blows the performance budget on pathological documents
// (see ARCHITECTURE.md, performance budget).
const maxHighlightFenceBytes = 50 << 10 // 50 KB

// Doc is a rendered markdown document delivered to the frontend.
type Doc struct {
	HTML  string `json:"html"`
	Title string `json:"title"`
	Path  string `json:"path"`
	Dir   string `json:"dir"`
}

// Renderer converts markdown files into sanitized HTML documents.
type Renderer struct {
	md     goldmark.Markdown
	policy *bluemonday.Policy
}

// New builds the render pipeline described in ARCHITECTURE.md.
func New() *Renderer {
	md := goldmark.New(
		goldmark.WithExtensions(
			extension.GFM,
			highlighting.NewHighlighting(
				highlighting.WithFormatOptions(
					chromahtml.WithClasses(true),
				),
			),
		),
		goldmark.WithParserOptions(
			parser.WithAutoHeadingID(),
		),
		// Raw HTML is passed through here and neutralized by bluemonday below.
		// It must never reach the webview unsanitized.
		goldmark.WithRendererOptions(
			html.WithUnsafe(),
		),
	)
	return &Renderer{md: md, policy: buildPolicy()}
}

func buildPolicy() *bluemonday.Policy {
	p := bluemonday.UGCPolicy()
	// chroma emits class-based highlighting on span/code/pre/div.
	p.AllowAttrs("class").OnElements("span", "code", "pre", "div")
	// Heading anchor ids generated by parser.WithAutoHeadingID().
	p.AllowAttrs("id").Matching(regexp.MustCompile(`^[\p{L}\p{N}\-_:.]+$`)).
		OnElements("h1", "h2", "h3", "h4", "h5", "h6")
	// GFM task-list checkboxes.
	p.AllowAttrs("type").Matching(regexp.MustCompile(`^checkbox$`)).OnElements("input")
	p.AllowAttrs("checked", "disabled").Matching(regexp.MustCompile(`^(|checked|disabled)$`)).OnElements("input")
	// UGCPolicy already allows img[src] with relative URLs, which covers the
	// rewritten /doc-asset/ routes, and a[href], tables, blockquotes, del, etc.
	return p
}

// RenderFile reads path from disk and renders it. The caller is responsible
// for scope-checking path before calling this.
func (r *Renderer) RenderFile(path string) (Doc, error) {
	abs, err := filepath.Abs(path)
	if err != nil {
		return Doc{}, fmt.Errorf("resolve path: %w", err)
	}
	src, err := os.ReadFile(abs)
	if err != nil {
		return Doc{}, fmt.Errorf("read %s: %w", abs, err)
	}
	return r.Render(abs, src)
}

// Render converts markdown source into a sanitized Doc. path must be the
// absolute path of the document; relative image sources are resolved against
// its directory and rewritten to the /doc-asset/ route.
func (r *Renderer) Render(path string, src []byte) (Doc, error) {
	dir := filepath.Dir(path)

	root := r.md.Parser().Parse(text.NewReader(src))
	title := extractTitle(root, src)
	if title == "" {
		title = strings.TrimSuffix(filepath.Base(path), filepath.Ext(path))
	}
	rewriteImageSources(root, dir)
	capOversizedFences(root)

	var buf bytes.Buffer
	if err := r.md.Renderer().Render(&buf, src, root); err != nil {
		return Doc{}, fmt.Errorf("render %s: %w", path, err)
	}

	sanitized := r.policy.SanitizeReader(&buf).String()
	return Doc{HTML: sanitized, Title: title, Path: path, Dir: dir}, nil
}

// extractTitle returns the text of the first level-1 heading, or "".
func extractTitle(root ast.Node, src []byte) string {
	var title string
	_ = ast.Walk(root, func(n ast.Node, entering bool) (ast.WalkStatus, error) {
		if !entering {
			return ast.WalkContinue, nil
		}
		if h, ok := n.(*ast.Heading); ok && h.Level == 1 {
			title = string(nodeText(h, src))
			return ast.WalkStop, nil
		}
		return ast.WalkContinue, nil
	})
	return strings.TrimSpace(title)
}

func nodeText(n ast.Node, src []byte) []byte {
	var buf bytes.Buffer
	for c := n.FirstChild(); c != nil; c = c.NextSibling() {
		switch t := c.(type) {
		case *ast.Text:
			buf.Write(t.Segment.Value(src))
		default:
			buf.Write(nodeText(c, src))
		}
	}
	return buf.Bytes()
}

// rewriteImageSources rewrites relative <img> destinations to the scope-checked
// asset route, resolved against the document directory. Absolute http(s)/data
// URLs are left untouched.
func rewriteImageSources(root ast.Node, dir string) {
	_ = ast.Walk(root, func(n ast.Node, entering bool) (ast.WalkStatus, error) {
		if !entering {
			return ast.WalkContinue, nil
		}
		img, ok := n.(*ast.Image)
		if !ok {
			return ast.WalkContinue, nil
		}
		dest := string(img.Destination)
		if rewritten, ok := RewriteAssetURL(dest, dir); ok {
			img.Destination = []byte(rewritten)
		}
		return ast.WalkContinue, nil
	})
}

// capOversizedFences strips the language info from fenced code blocks larger
// than maxHighlightFenceBytes. Without a language (and with language guessing
// off, the default), goldmark-highlighting falls back to a plain escaped
// <pre><code> block — no chroma tokenization, so render time stays bounded.
func capOversizedFences(root ast.Node) {
	_ = ast.Walk(root, func(n ast.Node, entering bool) (ast.WalkStatus, error) {
		if !entering {
			return ast.WalkContinue, nil
		}
		fence, ok := n.(*ast.FencedCodeBlock)
		if !ok || fence.Info == nil {
			return ast.WalkContinue, nil
		}
		size := 0
		lines := fence.Lines()
		for i := 0; i < lines.Len(); i++ {
			seg := lines.At(i)
			size += seg.Len()
			if size > maxHighlightFenceBytes {
				fence.Info = nil
				break
			}
		}
		return ast.WalkContinue, nil
	})
}

// RewriteAssetURL converts a local image reference into a /doc-asset/ route.
// It returns ok=false when the URL should be left as-is (remote, data:, or
// already an asset route).
func RewriteAssetURL(dest, dir string) (string, bool) {
	if dest == "" || strings.HasPrefix(dest, AssetRoutePrefix) || strings.HasPrefix(dest, "#") {
		return "", false
	}
	if u, err := url.Parse(dest); err == nil && (u.Scheme != "" || u.Host != "") {
		// http(s)://, data:, file:, etc. — leave remote/schemed URLs alone.
		return "", false
	}
	// Local path: strip any fragment/query-ish suffix conservatively (rare in
	// image refs), decode percent-encoding, resolve against the document dir.
	pathPart := dest
	if i := strings.IndexAny(pathPart, "#?"); i >= 0 {
		pathPart = pathPart[:i]
	}
	if decoded, err := url.PathUnescape(pathPart); err == nil {
		pathPart = decoded
	}
	if pathPart == "" {
		return "", false
	}
	abs := pathPart
	if !filepath.IsAbs(abs) {
		abs = filepath.Join(dir, abs)
	}
	abs = filepath.Clean(abs)
	return AssetRoutePrefix + "?p=" + url.QueryEscape(abs), true
}
