// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPrewarmState() {
  return window['go']['main']['App']['GetPrewarmState']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsWindowHidden() {
  return window['go']['main']['App']['IsWindowHidden']();
}

export function MarkPrewarmAsked() {
  return window['go']['main']['App']['MarkPrewarmAsked']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenWithSystemDefault(arg1) {
  return window['go']['main']['App']['OpenWithSystemDefault'](arg1);
}

export function PresentWindow() {
  return window['go']['main']['App']['PresentWindow']();
}

export function Ready(arg1) {
  return window['go']['main']['App']['Ready'](arg1);
}

export function RenderDocument(arg1) {
  return window['go']['main']['App']['RenderDocument'](arg1);
}

export function ResolveLink(arg1, arg2) {
  return window['go']['main']['App']['ResolveLink'](arg1, arg2);
}

export function SetPrewarm(arg1) {
  return window['go']['main']['App']['SetPrewarm'](arg1);
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}

export function Trace(arg1) {
  return window['go']['main']['App']['Trace'](arg1);
}
