// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';
import {render} from '../models';
import {links} from '../models';

export function GetSettings():Promise<settings.Settings>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function OpenWithSystemDefault(arg1:string):Promise<void>;

export function Ready():Promise<void>;

export function RenderDocument(arg1:string):Promise<render.Doc>;

export function ResolveLink(arg1:string,arg2:string):Promise<links.Resolution>;

export function SetSettings(arg1:settings.Settings):Promise<void>;
